version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build


